### ISSUE TITLE
DKIM verify example is failing

### ISSUE THREAD

**Issue by edevil** [stalwartlabs/mail-auth#19]
I just tried the example in `/examples/dkim_verify.rs` and it fails with:

```
thread 'main' panicked at 'assertion failed: result.iter().all(|s| s.result() == &DkimResult::Pass)', examples/dkim_verify.rs:52:5
```
it seems that the header parsing code does not handle header values that span multiple lines. Was this working before?

**Comment by mdecimus** [comment]
That is correct, the verification examples will fail because the message was signed with an invalid DKIM key for the fictitious domain name `football.example.com`. It just shows how to use the library, what is important is that the tests pass.
