### ISSUE TITLE
MTA /  MTA connection

### ISSUE THREAD

**Issue by stappersg** [stalwartlabs/mail-auth#2]
Is `mail-auth` a _Mail Transfer Agent_?
Or how to connect `mail-auth` with a _MTA_ like [postfix](https://www.postfix.org/)?

This project's `README.md` doesn't tell.

**Comment by stappersg** [comment]
Link to a [next-gen Mail Transfer Agent (MTA) written in Rust.](https://github.com/viridIT/vSMTP). No idea how it should connect with `mail-auth`, the URL might help, might add noise.

**Comment by mdecimus** [comment]
mail-auth is an e-mail authentication library, it does not send messages, it just validates the authenticity of an e-mail message using DKIM, ARC, SPF and DMARC.

An MTA that uses mail-auth will be released in a few months.
