### ISSUE TITLE
Incorrect body hash when content is empty

### ISSUE THREAD

**Issue by remipcomaite** [stalwartlabs/mail-auth#22]
I have an error verifying the DKIM signature of emails whose content is empty.
I believe there is a bug in the body hash calculation if the message body is empty.

Here are the tests I performed when the email is empty and when the email only contains the word "toto".

Empty:

https://mxtoolbox.com/deliverability/274cfab4-394e-474c-993d-9c1531f2f04f

Not empty:

https://mxtoolbox.com/deliverability/eb6c7a5a-5145-4290-baec-3a72bff09d70

**Comment by mdecimus** [comment]
Was that message signed by Stalwart? Because based on the `Received` headers it looks like it was signed by Postfix or OpenDKIM.
If both Stalwart and MX Toolbox fail to verify the message then it is probably a Postfix issue.

**Comment by remipcomaite** [comment]
Indeed, in my case, outgoing emails are processed by Postfix but they are signed by Stalwart.
These are the results of the tests I did with email addresses managed by Stalwart.
The test is carried out by sending an email to the address indicated here:
https://mxtoolbox.com/deliverability

**Comment by mdecimus** [comment]
Great, I'll check it out.

**Comment by mdecimus** [comment]
This has been fixed in `v0.3.7`.
