### ISSUE TITLE
SPF verify returning None for long domain names with valid SPF records

### ISSUE THREAD

**Issue by titussanchez** [stalwartlabs/mail-auth#33]
Hi,

I recently found some domain names in the wild that are fairly long. They are >63 characters and causing the SPF verification function to return a None even though a valid SPF record exists at the domain name.

I found this in `spf/verify.rs:91-93`
```rust
        if domain.is_empty() || domain.len() > 63 || !domain.has_labels() {
            return output.with_result(SpfResult::None);
        }
```

Based on [RFC 5321](https://www.rfc-editor.org/rfc/rfc5321#section-4.5.3.1.2) it looks like the 63 character limitation should be on the individual labels and not the total length of the domain. The total domain name length limit is 255 characters.

**Comment by mdecimus** [comment]
Hi,

Makes sense, can you submit a PR for this?
